### ISSUE TITLE
Instructions don't work for me

### ISSUE THREAD

**Issue by TorstenS73** [cyrusimap/cyrus-docker#1]
Hello!

I was quite happy to find some kind of "official" Docker support from the Cyrus project. At least I hope I did.

Just the instructions in your README.md don't work for me.

I tried:

`docker build -t cyrus-imapd-3.0.santiago - < santiago
`
That completed without any errors. Just then:

```
$ docker run -t -i cyrus-imapd-3.0.santiago
/entrypoint.sh: line 3: cd: /srv/cyrus-docker.git: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
/entrypoint.sh: line 5: ./testscript.sh: No such file or directory
```

I need to say it took me a moment to understand the logic behind

`docker build -t cyrus-imapd-3.0.santiago - < santiago
`
until I found out that santiago, tumbleweed, jessie etc. are names of different versions of different flavors of Linux which you use as a basis and that the files with that names are actually Dockerfiles.

So I tried some more besides santiago, but I got the same problem about entrypoint.sh all the time.

Next attempt:

`make all run
`
Leads to:

`W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/vivid-security/restricted/source/Sources  404  Not Found [IP: 91.189.88.161 80]`
(and several similar lines)

Does anyone have any more luck?

Is the stuff here a dead end anyway? Would be a pitty. It looked soo good.

Regards,
Torsten

**Comment by drzaiusx11** [comment]
looks like some of the linux distro files are missing the lines under the 'WORKDIR /srv' section:

```
RUN git config --global http.sslverify false && \
    git clone https://github.com/cyrusimap/cyrus-docker.git \
    cyrus-docker.git
```

**Comment by drzaiusx11** [comment]
also I think centos6 (santiago) is too old to run cyrus head, prob need a minimum of centos7 (maipo)

**Comment by rjbs** [comment]
The Makefile is a bit of a mess, but:
* `docker build .` in Debian should work
* there are regular builds in Docker Hub
* regular builds might move to GHCR
* if you still have (5yr later) requests, please let us know.
