### ISSUE TITLE
Clarify situation about official Docker image for Cyrus IMAP

### ISSUE THREAD

**Issue by marclaporte** [cyrusimap/cyrus-docker#3]
I see
https://hub.docker.com/u/cyrusimapd
https://cyrus.foundation/

But it's unclear to me what is status

There are others, but which one should we all converge on?
https://hub.docker.com/search?q=cyrus%20imap&type=image

Thanks!

**Comment by marclaporte** [comment]
Here is a recent one: https://hub.docker.com/u/cyrusimapdocker

**Comment by marclaporte** [comment]
One more: https://hub.docker.com/r/chmanie/hemhem-cyrus

**Comment by sstubbs** [comment]
I've also had issues finding an official image. It would be really great if there was one.

**Comment by elliefm** [comment]
The cyrus-imapd project seems to use the "cyrusimapdocker" one for Travis CI purposes: https://github.com/cyrusimap/cyrus-imapd/blob/823717b672fe3d662898c029b22941b915426930/.travis.yml#L11

I think this is as close as we've got to an "official" one.  It at least gets exercised by Travis on a regular basis.  I have no idea whether it's suitable for any other purpose.

My experience with docker has mostly been limited to trying to figure out why stuff breaks under docker, when it doesn't on a normal install... so I mostly see docker as an annoying extra abstraction layer, and try to avoid touching it if at all possible! :)

**Comment by MellowVoidUser** [comment]
I would love to see a podman image (which is basically a docker image without a daemon and can be run rootless :) )

**Comment by sstubbs** [comment]
ok thanks I will have a look at "cyrusimapdocker" image. I've been running Cyrus in docker for a few years without problems but having to build the images each time always means there might a problem. So I'm trying to find some way of being more sure it will work as I've been using master for jmap features which isn't very safe and I always need to test it in staging for some time. At least with 3.2 release all the jmap functionality I need is just about there so hopefully once this is out of beta it will be the last image I need until the next stable release.

**Comment by marclaporte** [comment]
It's not standalone, but it does include Cyrus IMAP:
https://github.com/fabiomontefuscolo/wikisuite-swarm/tree/master/wikisuite/resources

**Comment by marclaporte** [comment]
Now that Cyrus IMAP 3.2.0 has been released (with JMAP!), it would be fantastic to have it available via Docker:
https://lists.andrew.cmu.edu/pipermail/info-cyrus/2020-May/041225.html

**Comment by woj-tek** [comment]
3.4.0 was released over a year ago...

Mentioned [wikisuite-swarm](https://github.com/fabiomontefuscolo/wikisuite-swarm) is archived so not not tha viable.

**Comment by rjbs** [comment]
The "Cyrus Foundation" was a flash in the pan: https://www.fastmail.com/blog/the-year-of-the-cyrus-foundation/

I hope to make things more official via the GitHub Container Registry.  Meantime, don't hold your breath.  More information may be found on the dev list: https://cyrus.topicbox.com/groups/devel

**Comment by rjbs** [comment]
🫡  Will do in the not too distant future.  I've sort of just dropped into this project (after a long time at the periphery) and am getting a handle on things.  I agree with you: it is surprising, based on the README, to see that this isn't really "a Cyrus".  I think probably this will get new docs and new packaging over the next few months as I figure out the best way to ship the various pieces we have.
