### ISSUE TITLE
Stable vs development

### ISSUE THREAD

**Issue by marclaporte** [cyrusimap/cyrus-docker#6]
It would be fantastic to have two versions: Latest stable vs recent development snapshot (ex.: to test JMAP)

**Comment by sstubbs** [comment]
I've also had issues finding an official image. It would be really great if there was one.

**Comment by rjbs** [comment]
This ticket is ancient, so I'm going to close it.  But if you still care: I want more information, please!

Right now, this image just _prepares_ to build Cyrus, and needs to be put to work to actually build.  Do want some sort of change?  Maybe change an entrypoint to build a given head?
